Refactor :: apply SRP & improve matching return value
Took-Talk/TookTalk-Server-v2 pull request #36
Opened 2024-04-22 09:27 UTC by miraexhoi

## 관련 이슈
- https://github.com/Took-Talk/TookTalk-Server-v2/pull/35#discussion_r1574068858
- https://github.com/Took-Talk/TookTalk-Server-v2/pull/35#discussion_r1574122388
위 코드리뷰 참고해서 리팩토링 했습니다.
## 작업 내용
1. 단일 책임 원칙 적용
2. MatchingResponse 생성해서 반환값 수정
3. 중복 코드 제거 및 불필요한 파일 삭제

2024-04-22 14:02 UTC, jungsunghwa commented
단일 책임 원칙을 조금 더 지켜보려면 
`matchingService.matching()` 함수가 하는 일을 분해해서 봐야해요

지금하는 일을 정리해보면
1. userRepository 에서 UserEntity 검색
2. user.hidePassword(""); 
3. matchingRepository.findByMbti(mbti);
4. if (matchingUserEntity == null){
5. 각 결과에 맞는 MatchingUserEntity 반환

지금 미래님의 눈을 속이고 있지만, 이렇게 총 5가지인거에요. 
결국 `matchingService.matching()` 이 함수는 단일 책임 원칙에 위배되는거죠!

실제로 matching() 에 필요한 작업이 뭔지? 잘 고민해볼 필요가 있어요.
데이터 베이스에서 가져오는 코드도 한가지에 작업 이라는 것을 잊으면 안됩니다!

2024-04-22 14:03 UTC, jungsunghwa commented
결과 = 반려 입니다. 다시써서 제출하세요~

2024-04-22 14:08 UTC, jungsunghwa requested changes
ㅇ

2024-04-22 14:51 UTC, miraexhoi commented
제 눈이 속고 있을거라고는 생각도 못 했네요 하하..
얼른 고쳐오겠습니다 🫡🫡

2024-04-23 00:25 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/dto/response/MatchingResponse.java
> +    private UserEntity userInfo;
`entity`를 바로 반환하게 될 때에는 JPA 양방향 순환참조 문제가 생길 가능성이 있습니다. [참고](https://dev-coco.tistory.com/133)

반환시에는 새로운 객체를 만들어 반환하는게 좋아요 :)
mapping 하는 과정이 귀찮다면 `mapStruct` 라이브러리를 공부해보는 것도 좋아요 [참고](https://medium.com/naver-cloud-platform/기술-컨텐츠-문자-알림-발송-서비스-sens의-mapstruct-적용기-8fd2bc2bc33b)

2024-04-23 00:25 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +            return removeFromWaitingList(user, matchingUserEntity);
`if`문 안에서 데이터를 `return`해주고 있으니 `else`예약어를 사용하지 않는 것이 가독성 부분에서 더 좋아보입니다

2024-04-23 00:25 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        hideUserPassword(user);
클래스 내부의 데이터를 제어하는 영역이니, 
해당 함수는 비즈니스 로직을 제어하는 `service`에서 관리되는 것 보다. 

`UserEntity`에서 관리되는 것이 더욱 올바를 것 같네요 :)

2024-04-23 00:25 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +                    throw new RuntimeException(e);
`RuntimeException`으로 바로 `throw`하는 것 보다는 예측 가능한 에러로 핸들링 하는 것이
추 후 에러가 생겼을 때, 파악하기 더 좋습니다 :)

2024-04-23 00:29 UTC, krung2 commented
적다 보니 심화적인 부분이 많아진 것 같은데... 궁금하거나 모르겠는거 있으면 꼭 물어봐주세요!

2024-04-23 03:18 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/dto/response/MatchingResponse.java
> +    private UserEntity userInfo;
mapStruct를 조금 찾아봤는데 어려워서 적용까지는 시간이 좀 걸릴거 같네요 😥
그렇지만 좋은 라이브러리 인거 같아서 따로 공부해보고 싶어요!
일단은 response 만들어 반환되도록 구현하고 mapStruct 이해 한 후에 적용해 보겠습니다 :)

2024-04-23 03:21 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +            return removeFromWaitingList(user, matchingUserEntity);
수정 했습니다!

2024-04-23 03:21 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        hideUserPassword(user);
넵 수정 했습니다! [c84e4f3](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/c84e4f32786347e22faf5004f5f4f666cbd86e10)

2024-04-23 03:24 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +                    throw new RuntimeException(e);
error code 정의하고 custom exception 만들어 핸들링 하면 될까요?

2024-04-23 04:03 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/dto/response/MatchingResponse.java
> +    private UserEntity userInfo;
당장에는 굳이 `mapStruct`를 사용해서 맵핑하지 않아도 돼요.

JPA 양방향 순환참조 문제의 해결 방법이 다양해서 다른 방법으로 해결해도 충분합니다~

2024-04-23 04:04 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +                    throw new RuntimeException(e);
넵~

2024-04-23 04:08 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        hideUserPassword(user);
엇... 전달하는 과정에서 오해가 있었나보네요.
`findUserByNickname`라는 함수는 `repository`로 부터 데이터를 가져오는 비즈니스 로직이니, `service`에 있는게 적합하고.

`hideUserPassword`함수 같은 경우 `setter`를 사용해서 클래스 내부 데이터를 수정하는 함수이니 `entity`안에 들어가는 적합하다는 것을 말하고 싶었습니다~!

2024-04-23 04:24 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    public void fixUserData(UserInfoRequest request, String nickname, MultipartFile multipartFile){
해당 함수도 `단일 책임 원칙`에 위반되고 있네요 :0
이것도 같이 확인 해봐요 :)

2024-04-23 06:39 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/dto/response/MatchingResponse.java
> +    private UserEntity userInfo;
아 그렇군요! 그렇게 하도록 하겠습니다 감사합니다 :)

2024-04-23 06:40 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        hideUserPassword(user);
제가 잘 못 이해한 거 같습니다.. 
말씀 주신대로 다시 `hideUserPassword` 함수를 `entity` 로 옮겼습니다! [895ee26](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/895ee26a0f45b85d4d27444047eac6d47b077fe2)

2024-04-23 06:40 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    public void fixUserData(UserInfoRequest request, String nickname, MultipartFile multipartFile){
넵 확인 후 수정 했습니다-! [36ebcca](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/36ebcca86a7a48276a0de5dc79fb0a94f532fae2)

2024-04-23 08:22 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/entity/user/UserEntity.java
> +    }
이 함수를 `static`함수로 선언하신 이유가 있을까요??
꼭 정답이 아니라도 작성하실때 하셨던 생각을 공유해주세요!

2024-04-23 08:22 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
`ifPresent`로 구현하신 이유가 있을까요?

2024-04-23 08:22 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
유저의 정보를 수정하는 함수에는 항상 존재하는 유저의 `id`가 들어와야됩니다.
조회되지 않는 유저(존재하지 않는 유저)가 들어왔을 때에는 `4xx` 클라이언트 오류를 반환하는건 어떨까요?

2024-04-23 08:22 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        }
수정해주신 함수에도, `단일 책임 원칙`을 벗어나고 있네요!

2024-04-23 08:22 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        }
현재 함수가 하는 역할은 2가지입니다.
1. 이미지를 업로드 한다 .
2. `user`데이터를 업데이트한다.

`단일 책임 원칙`의 목표는 코드의 의존성과 결합도를 줄이기 위함입니다.
해당 함수에 적용해보면,

유저의 프로필 사진은 1장이다. -> 유저의 프로필 사진은 여러장도 가능하다.
이러한 변경사항이 생길 시 **업로드와 관련된 함수에 수정이 필요하다.**
라는 연쇄작용이 생기게 됩니다! 결합도가 높아지는 거죠!

2024-04-23 08:22 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        }
ps. 추가로, 유저와 이미지 업로드 로직은 서로 다른 도메인을 가지고 있으니 다른 `service`로 분리해보는건 어떨까요?

2024-04-23 10:22 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
의도는 유저 데이터에 값이 들어있을때 작업을 하고 아닐때는 수행하지 않으려는 의도였고 구현하기 쉬워서 저렇게 구현했습니다 😅

2024-04-23 11:02 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        }
[da12f32](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/da12f325323c593ca4949765f412d3438093a1dd) 일단은 분리 작업을 했는데 궁금한 점이 있어요!
`fixImage` 는 UserEntity에서 가져오고 있는데 분리 해야 하는 이유가 있나요?

2024-04-23 11:21 UTC, miraexhoi commented
> 첨언하자면 함수별 단일 책임원칙을 잘 지킨 것 같습니다!
> 
> 아래 두가지를 명심하고 연구해보면 좋아요.
> 
> 1. service도 단일 책임 원칙이 적용되어있나?
> 2. service, controller, repository 레이어 의 경계가 명확하게 분리되어있나?
> 
> service의 로직 중 DB에서 불러오던 작업을 API로 불러오면 어떻게처리하지? 
혹은 2개의 Entity를 조합해서 가지고 와야하면 어떻게 처리해야하지?
> 
> 처럼 로직 개발 보다는 확장성 측면으로 고민하는 개발을 해야합니다!
> 
> ps. 우리가 너무 괴롭히고 있으면 🥕을 흔들어주세요

전혀요! 오히려 바쁘실텐데 신경써 주셔서 너무 감사한 마음 밖에 없습니다 :)
앞으로 위 두가지 내용 뿐만 아니라 여러 고민을 함께 하면서 개발 하겠습니다 감사합니다!

2024-04-24 00:21 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/entity/user/UserEntity.java
> +    }
좋습니다 :+1:

미래님이 이전에 하셨던 것 처럼 `static`을 이용하여 내부 데이터를 변경하게 되면,
객체지향 프로그래밍 특성 중 하나인 `캡슐화`에 어긋나게 됩니다!

2024-04-24 00:26 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
유저의 정보가 변경 되지 않았는데, `200 OK`를 보내는 것은 클라이언트에게 큰 혼란을 줄 수 있습니다.
-> 클라이언트 입장에서는 정보가 변경되었다는 메시지를 전달 받았지만, 아무런 정보도 변경 되지 않았음.

보통은 `http status code`중 `4xx`를 이용하여 
클라이언트에서 잘못된(존재 하지 않은) 요청을 보냈다고 클라이언트 사이드 에러를 반환 해줍니다!

클라이언트랑 이야기 해보고, 수정을 고려하는 걸 추천드립니다~ :)
(상황에 따라 에러를 반환하지 않고 `200 OK`로 처리하는 경우도 있습니다)

2024-04-24 01:09 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        }
좋은 질문입니다!

이런 경우에는 함수의 이름부터 접근해보면 이해하기가 편하실 거에요!

`updateUserImage`는 유저 이미지를 업데이트 한다고 이해됩니다.
하지만 실제로는 `이미지 업로드`, `유저 프로필 업데이트` 두 가지 역할을 하게 된 것이죠.

2024-04-24 01:21 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        user.hideUserPassword(user);
비밀번호를 숨기는 로직은 앞으로, `findUserByNickname`함수를 호출하여 `UserEntity`를 가져올 때마다 사용 될 것 같은데 `findUserByNickname`함수로 넣어버리는건 어떨까요?

2024-04-24 01:21 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
혹시나 적용하시게 되면, 
`Jpa`에서 `find`와 `get`의 차이도 공부해보시는 것도 좋습니다 :)

2024-04-24 01:27 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    private String updateUserImage(MultipartFile multipartFile) {
로직을 보니, `updateUserImage`라는 함수명 보다 이미지를 업로드 한다는 내용이 더 알맞을 것 같네요!

2024-04-24 01:27 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    private String updateUserImage(MultipartFile multipartFile) {
유저와 관심사(도메인)이 다른 것 같아 보여, 
`class`를 분리해주는 것도 좋아 보입니다 👀

2024-04-24 01:27 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>      }
이미지만 별도로 수정이 가능한 것일까요?
함수가 별도로 존재하는 이유가 궁금합니다!

2024-04-24 01:27 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    public void fixUserData(UserInfoRequest request, String nickname, MultipartFile multipartFile){
(의견)
`fix`라는 단어는 `(망가진 것, 잘못된 것)을 고치다`, `고정하다`는 의미를 가지고 있습니다.

`update`, `modify` 이런 단어들이 더욱 잘 어울릴 것 같습니다.

2024-04-24 02:55 UTC, jungsunghwa commented on src/main/java/com/mirae/tooktalk/domain/user/entity/user/UserEntity.java
> +    }
저기 지금 user 인스턴스 넘기는거 무ㅏㄴ가 이상하지 않나요??? this 키워드 써야하는거 아닐까요

2024-04-24 03:14 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/entity/user/UserEntity.java
> +    }
어 그러네요... 인스턴스를 넘기는게 아니라
함수 내부에서 this로 하는게 맞네요

2024-04-24 11:11 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/entity/user/UserEntity.java
> +    }
헉 바로 수정 했습니다-! [051c3ca](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/051c3ca98f53a0a886c61239239df6e0b8a6a185)

2024-04-24 11:33 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
항상 `find` 만 사용해와서 `get` 에 대한 지식이 없었네요.

공부해보니 `find` 는 데이터를 직접 가져오고 `get` 은 프록시를 만들어 조회하며 
`find` 는 DB에 해당 값이 없으면 `null` 을 반환하지만 `get` 은 NPE가 발생 한다고 하네요!

`get` 사용도 생각해 봐야겠습니다 :)

2024-04-24 11:53 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        user.hideUserPassword(user);
말씀 주신 대로 변경 해봤습니다! [eabed9c](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/eabed9c66c1dbb33dc48ab3372d09bf26c091002)
```java
public MatchingResponse matching(Authentication authentication, String mbti){
        UserEntity user = findUserByNickname(authentication.getName());
        MatchingUserEntity matchingUserEntity = findMatchingUserByMbti(mbti);

        return handleMatchingResult(user, matchingUserEntity, mbti);
}

private UserEntity findUserByNickname(String nickname) {
        UserEntity user = userRepository.findByNicknameEquals(nickname)
                .orElseThrow(() -> new NoSuchElementException("User not found"));
        user.hideUserPassword();

        return user;
}
```

그러나 `UserRepository` 에 `findByNicknameEquals` 가 구현되어 있는걸 한번 더 구현한거 같아서
`findUserByNickname` 함수를 제거 하고 함수가 제거 되었으니 
`hideUserPassword` 를 그대로 두고 아래처럼 수정하는 것은 어떻게 생각 하시나요?
```java
public MatchingResponse matching(Authentication authentication, String mbti){
        UserEntity user = userRepository.findByNicknameEquals(authentication.getName()).get();
        MatchingUserEntity matchingUserEntity = findMatchingUserByMbti(mbti);
        user.hideUserPassword();
        
        return handleMatchingResult(user, matchingUserEntity, mbti);
}
```

2024-04-24 13:10 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    private String updateUserImage(MultipartFile multipartFile) {
[b5fdefa](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/b5fdefa593beadc2faf598f6b1bf2b049fc2081b) 

`S3Upload` 라는 클래스가 있어요!
그래서 그걸 사용하였고, `updateUserImage` -> `uploadUserImage` 로 함수명 또한 변경하였습니다.

또한 저번에 말씀하신 대로 `RuntimeException` 으로 바로 `throw` 하는 것 보다는 `log` 를 남겨 예측 가능 하도록 하였습니다.
( ++ `Custom Exception` 을 잘 쓰기 위해서는 공부가 조금 더 필요할거 같아요! )

2024-04-25 00:28 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
get을 했을때 데이터를 찾지 못하면, `EntityNotFoundException`를 던져버리니 에러 핸들링은 필수겠죠! :) [참고자료](https://docs.spring.io/spring-data/jpa/docs/current/api/org/springframework/data/jpa/repository/JpaRepository.html#getReferenceById(ID))

2024-04-25 00:59 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        user.hideUserPassword(user);
좋은 접근입니다! :+1: :+1:

`findUserByNickname`함수를 분리하는 이유는 코드의 가독성과 재활용성을 향상시키기 위함입니다!
함수의 이름만으로 어떤 동작을 하는 함수인지 한번에 파악할 수 있고,
다른 서비스나 다른 함수에서 이름으로 유저를 찾는 로직이 필요하게 된다면 해당 함수를 이용하여 여러 곳에 동일한 함수가 만들어지는 것 막을 수 있습니다 .

현재는 테스트 코드가 존재하지 않지만, 
추 후 쉬운 테스트와 유지보수(가독성, 재활용성 등등)를 생각하시면서 코드를 짜려고 노력해보는 것이 좋습니다!
    
ps. 아래 케이스에서 `userRepository.findByNicknameEquals`함수에서 `Optional`로 조회하여, `null`을 체크하는 부분도 빠지게 되네요 😄

2024-04-25 01:10 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        user.hideUserPassword(user);
사실 `service`에서 `user.hideUserPassword()`비밀번호를 초기화 하는 방법보다

`Repository`에서 조회할 때 `password`가 존재하지 않는 클래스 혹은 인터페이스로 받아온다거나,
`ResponseDto`에서 맵핑하면서 제외해주는게 더 좋아 보이긴 하네요! 🤔

2024-04-25 01:20 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    private String updateUserImage(MultipartFile multipartFile) {
`@ControllerAdvice`, `@ExeptionHandler`이 두 어노테이션을 공부해보고 활용할 수 있는 방법을 찾아봐요!
에러 핸들링만 잘 해둬도 유지보수 하기 100000000배는 더 편해집니다...

ps. 코드 짤때도 비즈니스 로직에만 집중할 수 있구요.

2024-04-25 01:29 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>      }
그렇다면 업데이트 하는 로직은 `updateUserData`함수에 합쳐보는건 어떨까요?
유저의 정보를 업데이트 하는 로직이 2개가 생긴 것 같네요!

`updateUserImage(multipartFile)`를 하고 에러를 핸들링 하는 함수를 하나로 빼는거죠!

2024-04-25 11:42 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>      }
넵, 적용해서 두 함수 병합 했습니다~! [962d2c7](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/962d2c7ce0484bc9b846696bb0d38c7eb0b7424a)

2024-04-25 11:43 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    private String updateUserImage(MultipartFile multipartFile) {
아하 감사합니다 ㅎㅎ

2024-04-25 11:55 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        user.hideUserPassword(user);
앗 그러면 아래 케이스로 수정 하겠습니다 :)

2024-04-25 11:55 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/chat/service/MatchingService.java
> +        user.hideUserPassword(user);
> 사실 `service`에서 `user.hideUserPassword()`비밀번호를 초기화 하는 방법보다
> 
> `Repository`에서 조회할 때 `password`가 존재하지 않는 클래스 혹은 인터페이스로 받아온다거나, `ResponseDto`에서 맵핑하면서 제외해주는게 더 좋아 보이네요!! 🤔

`QueryDSL` 같은 라이브러리를 사용한다면 패스워드 빼고 조회 할 수도 있을거 같네요!

2024-04-25 11:56 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
넵 명심하겠습니다~

2024-04-26 00:53 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>          Optional<UserEntity> user = userRepository.findByNicknameEquals(nickname);
그리고, 갑자기 든 생각인데 이름으로 대상을 검색하면

`[최미래, 정성화, 신중빈, 신중빈1]` 데이터가 이 처럼 있을 때
`신중빈`으로 검핵하게 된다면 항상 `신중빈`이 반환됩니다.
+`LIKE %...%`로 검핵하게 되어 인덱스를 타지 못해 조회 비용이 높은 것도 덤이죠!

따라서 해당 로직처럼 `특정 하나의 데이터`를 업데이트, 삭제 할 때에는 되도록
해당 데이터를 대표할 수 있는 `PK`값, `unique`한 컬럼을 사용하는 것을 권장합니다!
+되도록이면 `index`를 탈 수 있는 방법으로 조회하는게 좋아요 :)

2024-04-26 00:53 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +            }
이미지 업로드 중 생기는 에러 핸들링 부분은 `유저의 정보를 업데이트한다.`에 알맞지 않은 것 같아요.

이미지를 업로드하는 함수를 따로 분리하여 에러 핸들링을 하고, 
업로드한 이미지 링크를 반환하는 함수로 따로 분리하는건 어떨까요?
추 후 다른 API에서 재활용 하기 위해서는 `ImageService`로 분리하는 것이 더욱 좋아 보이구요 :)

2024-04-26 13:07 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +            }
넵 선배님 말씀 적용해서 함수 수정 하였고, 
동아리 선배님이 보통 이미지 api 는 분리하는게 일반적이라고 하셔서
이미지 업로드 api와 user 수정 api를 분리하였습니다! [73b27b5](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/73b27b5a0c97cd707295f9794e09a1264a975941) [84f8230](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/84f8230e42cfc12656962f8d109d12874866d1da)

2024-04-26 13:08 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>          Optional<UserEntity> user = userRepository.findByNicknameEquals(nickname);
`jpa` 에서 `findByNicknameEquals` 를 호출하면 값이 완전히 같은걸 가져오는 걸로 알고있고 
`findByNicknameContains` 는 값이 들어 있으면 가져오는 걸로 알고 있습니다.
그래서 `findByNicknameContains` 를 사용한다면 `신중빈, 신중빈1` 둘 다 조회 할 수도 있겠네요..

제 의도는 완전 똑같은 이름일 경우에만 적용하는 거라서 `findByNicknameEquals` 를 사용했습니다!


ps. 되도록이면 `index` 나 `PK` 값으로 조회 하려고 노력하도록 하겠습니다 :)

2024-04-27 07:02 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>          Optional<UserEntity> user = userRepository.findByNicknameEquals(nickname);
제가 `Equals`랑 `Contains`를 헷갈렸나보네요.
`Equals`면 유저 검색엔 좋을 것 같습니다!

조회 할때는 최대한 `index`를 사용하여 조회할 수 해주세요!

2024-04-27 11:47 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>          Optional<UserEntity> user = userRepository.findByNicknameEquals(nickname);
넵 :)

2024-04-27 11:51 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
>      }
> 유저의 정보를 업데이트 하는 로직이 2개가 생긴 것 같네요... 그렇다면 업데이트 하는 로직은 `updateUserData`함수에 합쳐보는건 어떨까요?
> 
> `updateUserImage(multipartFile)`를 하고 에러를 핸들링 하는 함수를 하나로 빼는거죠! 에러 핸들링을 하는거 까지가 하나의 로직이니까요~

적용해서 코드 수정 했습니다! [5efdd4c](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/5efdd4cad2da49e300f3406cf8367697773e3f8a) [3f7a24f](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/3f7a24fffc6f4084abc82bc1959d747ee7d2d294)

2024-04-27 11:52 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +    private String updateUserImage(MultipartFile multipartFile) {
> `@ControllerAdvice`, `@ExeptionHandler`이 두 어노테이션을 공부해보고 활용할 수 있는 방법을 생각해봐요! 에러 핸들링만 잘 해둬도 유지보수 하기 100000000배는 더 편해집니다...
> 
> ps. 코드 짤때도 비즈니스 로직에만 집중할 수 있구요.

적용해서 코드 수정 했습니다! [5efdd4c](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/5efdd4cad2da49e300f3406cf8367697773e3f8a) [3f7a24f](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/3f7a24fffc6f4084abc82bc1959d747ee7d2d294)

2024-04-29 00:21 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
> 유저의 정보가 변경 되지 않았는데, `200 OK`를 보내는 것은 클라이언트에게 큰 혼란을 줄 수 있습니다. -> 클라이언트 입장에서는 정보가 변경되었다는 메시지를 전달 받았지만, 아무런 정보도 변경 되지 않았음.
> 
> 보통은 `http status code`중 `4xx`를 이용하여 클라이언트에서 잘못된(존재 하지 않은) 요청을 보냈다고 클라이언트 사이드 에러를 반환 해줍니다!
> 
> 클라이언트랑 이야기 해보고, 수정을 고려하는 걸 추천드립니다~ :) (특수한 경우에는 에러를 반환하지 않고 `200 OK`로 처리하는 경우도 있습니다)

해당 부분 생각 해보셨나요~?

2024-04-29 00:24 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/global/common/S3/S3Controller.java
> +    private final S3Uploader s3Uploader;
`S3Controller`를 사용하는 것도 좋지만, `imageController`로 사용하고 
이미지를 업로드 기능을 하는 컨트롤러로 사용하는 건 어떨까요?

`service`레이어와 `repository`레이어를 나누는 이유와 연관지어 생각해보면 좋을 것 같습니다!

2024-04-29 00:27 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/global/common/S3/S3Controller.java
> +    private final S3Uploader s3Uploader;
힌트를 조금 드리자면, `S3`컨트롤러 - `S3`를 이용하여 파일을 업로드 하는 기능을 담고있음.

하지만 추 후에 `S3`가 아닌, `GCP cloud storage`, `NCP object storage`를 사용하게 된다면,
업로드를 하는 `controller`가 계속 생기게 되겠네요.

2024-04-30 04:30 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/global/common/S3/S3Controller.java
> +        return ResponseEntity.ok().body(s3Uploader.upload(multipartFile, "profile pic"));
넵 옮겼습니다 :) [e37a00f](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/e37a00ff13e42d863415a859fba2ed8b6cc9d7f4)

2024-04-30 04:34 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/global/common/S3/S3Controller.java
> +    private final S3Uploader s3Uploader;
[b002c6d](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/b002c6db2034f824f0bf421b1715d33714625b06) `S3Controller` `ImageController` 로 변경하였고 
이미지를 업로드 기능을 하는 컨트롤러로 사용 할 것입니다!

앞으로는 추후에 추가될 부분도 고려하겠습니다 :)

2024-04-30 05:08 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
일단 `isPresent` 을 사용하지 않고 구현해 봤는데 확인 부탁드립니다.. [5e62c97](https://github.com/Took-Talk/TookTalk-Server-v2/pull/36/commits/5e62c97bafa0a8d44b707f61a70195fac536f608)

2024-04-30 06:37 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/image/controller/ImageController.java
> +    public ResponseEntity<S3Dto> uploadImage(@RequestPart("image") MultipartFile multipartFile) {
`Dto`이름은 아직 `S3`네요 😄

2024-04-30 06:37 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/image/service/ImageService.java
> +            return S3Dto.builder().imgUrl(s3Uploader.upload(multipartFile, "picture")).build();
`responseDto`로 변경하는 작업은 `controller`에서 처리해도 괜찮지 않을까요?

비즈니스 로직의 복잡도를 고려해서 생각해봐요~

2024-04-30 06:48 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/user/service/user/UserServiceImpl.java
> +        });
확인 했습니다! 잘하셨어요!

2024-04-30 10:36 UTC, miraexhoi commented on src/main/java/com/mirae/tooktalk/domain/image/service/ImageService.java
> +            return S3Dto.builder().imgUrl(s3Uploader.upload(multipartFile, "picture")).build();
음.. 보통 매핑 작업은 `service` 레이어나 `mapper` 클래스를 따로 생성해서 만들지 않나요?
`controller` 에서 `builder` 작업을 시도하면 코드의 가독성이 떨어질거 같아요..!

2024-04-30 12:18 UTC, krung2 commented on src/main/java/com/mirae/tooktalk/domain/image/service/ImageService.java
> +            return S3Dto.builder().imgUrl(s3Uploader.upload(multipartFile, "picture")).build();
음.. 제가 service에서 반환 클래스를 따로 생성해서 하는걸로만 생각하고 있었네요.

제가 고려했던 부분은 서비스를 다른 곳에서 재 사용 할 때 responseDto로 오게되면 문제가 있을 것이라 생각했습니다.

Builder로 사용한다면 미래님이 말씀하신 것 처럼 서비스에 있는게 더욱 올바르겠네요! 😃

좋습니다~!

2024-05-01 01:58 UTC, miraexhoi commented
너무 유익했고 크게 성장할 수 있었던 시간 이였습니다 :)
정말 감사합니다-!

2024-05-01 02:04 UTC, merged

2024-05-01 23:57 UTC, krung2 commented
다음에도 원하시면 PR 리뷰어에 넣어주시고, 카톡 해주세요!

언제든 환영입니다 😄